### ISSUE TITLE
Odmítnutí permission

### ISSUE THREAD

**Issue by jiriadamec** [Licho1/ZenID-android-sample#16]
V případě že user odmítne permission pro přístup ke kameře, tak `DocumentPictureView` i `FaceLivenessView` zamrzne a s tím i celá appka, user musí pouze zabít appku.

**Comment by tomaslad** [comment]
Každé naše "CameraView" (DocumentPictureView, FaceLivenessView atd.) ve výchozím nastavení automaticky kontroluje camera permission. Případně se znovu doptává uživatele o povolení při přístupu ke kameře. Pokud si uživatel vybere neudělit přistup s možností "don't ask again" tak tuto feature prosím deaktivujte viz ukázka https://github.com/Licho1/ZenID-android-sample/blob/master/basic-sample/src/main/java/cz/trask/zenid/sample/ui/SelfieActivity.java
